const records = [];
const ingredients = [];
const flavorOrder = [];
const $ = selector => document.querySelector(selector);
const selected = id => id === 'flavors' ? [...flavorOrder] : [...document.querySelectorAll(`#${id} .selected`)].map(button => button.dataset.value);

function escapeHtml(value) { return value.replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char])); }
function renderIngredients() { const quick = ['小麦粉', '白砂糖']; $('#ingredientChips').innerHTML = [...ingredients.map((item, index) => `<span class="chip">${escapeHtml(item)}<button type="button" data-index="${index}" aria-label="删除${escapeHtml(item)}">×</button></span>`), ...quick.filter(item => !ingredients.includes(item)).map(item => `<button type="button" class="quick-ingredient" data-ingredient="${item}">${item}</button>`)].join(''); }
function renderRecords() { $('#emptyState').hidden = records.length > 0; $('#records').innerHTML = records.map(record => `<article class="record ${record.preference === '偏好吃' ? 'preference-good-card' : record.preference === '偏难吃' ? 'preference-bad-card' : ''}" data-id="${record.id}"><div class="record-content"><div class="record-image-box">${record.image_path ? `<img class="record-image" src="${record.image_path}" alt="${escapeHtml(record.name || '食物图片')}" />` : ''}</div><div class="record-info"><div class="record-top"><div class="record-title"><span class="record-name">${escapeHtml(record.name || '未命名食物')}</span></div><div class="record-side"><div class="record-summary">${record.brand_name ? `<span class="record-brand">${escapeHtml(record.brand_name)}</span>` : ''}${record.flavors.length ? `<div class="record-tags">${record.flavors.map(value => `<span class="record-tag">${escapeHtml(value)}</span>`).join('')}</div>` : ''}</div></div><div class="repurchase-actions"><button class="repurchase-choice" data-value="偏好吃" type="button">偏好吃</button><button class="repurchase-choice" data-value="偏难吃" type="button">偏难吃</button></div><div class="record-meta">食材：${record.ingredients.map(escapeHtml).join('、')}</div></div></div></article>`).join(''); }
function restoreRecordSide(card) { card.classList.remove('expanded'); }
let page = 1;
let hasMoreRecords = true;
let loadingRecords = false;
async function loadRecords(reset = true) { if (loadingRecords || (!reset && !hasMoreRecords)) return; loadingRecords = true; const nextPage = reset ? 1 : page + 1; const params = new URLSearchParams({ page: nextPage, limit: 5, search: $('#recordSearch').value.trim() }); const result = await (await fetch(`/api/foods?${params}`)).json(); if (reset) records.length = 0; records.push(...result.items); page = nextPage; hasMoreRecords = records.length < result.total; renderRecords(); loadingRecords = false; }

$('#addIngredient').addEventListener('click', () => { const input = $('#ingredientInput'); const value = input.value.trim(); if (!value || ingredients.includes(value)) return; ingredients.push(value); input.value = ''; $('#formError').textContent = ''; renderIngredients(); input.focus(); });
$('#ingredientInput').addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); $('#addIngredient').click(); } });
$('#ingredientChips').addEventListener('click', event => { const quick = event.target.closest('.quick-ingredient'); if (quick) { ingredients.push(quick.dataset.ingredient); renderIngredients(); return; } const index = event.target.dataset.index; if (index === undefined) return; ingredients.splice(Number(index), 1); renderIngredients(); });
$('#flavors').addEventListener('click', event => { const choice = event.target.closest('.choice'); if (!choice) return; const value = choice.dataset.value; const index = flavorOrder.indexOf(value); if (index >= 0) flavorOrder.splice(index, 1); else flavorOrder.push(value); });
document.addEventListener('click', async event => { if (event.target.closest('.reason-form')) return; const repurchase = event.target.closest('.repurchase-choice'); if (repurchase) { const card = repurchase.closest('.record'); await fetch(`/api/foods/${card.dataset.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ preference: repurchase.dataset.value }) }); await loadRecords(); return; } const card = event.target.closest('.record'); if (card) { const expanded = document.querySelector('.record.expanded'); if (expanded && expanded !== card) restoreRecordSide(expanded); if (expanded === card) { restoreRecordSide(card); return; } card.classList.add('expanded'); return; } const expanded = document.querySelector('.record.expanded'); if (expanded) { restoreRecordSide(expanded); return; } const choice = event.target.closest('.choice'); if (choice) choice.classList.toggle('selected'); const preference = event.target.closest('#preference button'); if (!preference) return; document.querySelectorAll('#preference button').forEach(button => button.classList.remove('selected')); preference.classList.add('selected'); });
document.addEventListener('click', event => { const button = event.target.closest('.repurchase-choice[data-value="偏难吃"]'); if (!button) return; event.preventDefault(); event.stopImmediatePropagation(); const actions = button.closest('.repurchase-actions'); actions.innerHTML = `<form class="reason-form"><input required placeholder="请输入难吃理由" /><button type="submit">确认</button></form>`; actions.querySelector('input').focus(); }, true);
document.addEventListener('submit', async event => { const form = event.target.closest('.reason-form'); if (!form) return; event.preventDefault(); const card = form.closest('.record'); const reason = form.querySelector('input').value.trim(); if (!reason) return; await fetch(`/api/foods/${card.dataset.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ preference: '偏难吃', dislike_reason: reason }) }); await loadRecords(); }, true);

$('#imageInput').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; $('#imagePreview').src = URL.createObjectURL(file); $('#imagePreview').hidden = false; });
async function compressImage(file) { const image = await new Promise((resolve, reject) => { const value = new Image(); value.onload = () => resolve(value); value.onerror = reject; value.src = URL.createObjectURL(file); }); const scale = Math.min(1, 320 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); return new Promise(resolve => canvas.toBlob(resolve, 'image/jpeg', .35)); }

$('#foodForm').addEventListener('submit', async event => { event.preventDefault(); if (!ingredients.length) { $('#formError').textContent = '没有添加食材'; $('#ingredientInput').scrollIntoView({ behavior: 'smooth', block: 'center' }); return; } const saveButton = $('.save-fixed'); saveButton.disabled = true; saveButton.textContent = '保存中'; const file = $('#imageInput').files[0]; let imagePath = ''; if (file) { const form = new FormData(); form.append('image', await compressImage(file), 'food.jpg'); imagePath = (await (await fetch('/api/upload', { method: 'POST', body: form })).json()).path; } const record = { name: $('#dishName').value.trim(), brand_name: $('#brandName').value.trim(), ingredients: [...ingredients], flavors: selected('flavors'), preference: $('#preference .selected')?.dataset.value || '', image_path: imagePath }; await fetch('/api/foods', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(record) }); records.length = 0; await loadRecords(); event.target.reset(); $('#imagePreview').hidden = true; ingredients.length = 0; document.querySelectorAll('.selected').forEach(item => item.classList.remove('selected')); renderIngredients(); $('#formError').textContent = ''; saveButton.disabled = false; saveButton.textContent = '保存记录'; });
$('#recordSearch').addEventListener('input', () => loadRecords(true));
$('#clearSearch').addEventListener('click', () => { $('#recordSearch').value = ''; loadRecords(true); $('#recordSearch').focus(); });
window.addEventListener('scroll', () => { if (window.innerHeight + window.scrollY >= document.documentElement.scrollHeight - 160) loadRecords(false); });
const originalRenderRecords = renderRecords;
renderRecords = () => { originalRenderRecords(); document.querySelectorAll('.record-meta').forEach(item => { item.textContent = item.textContent.replace(/^食材：/, ''); }); document.querySelectorAll('.record').forEach(card => { const record = records.find(item => String(item.id) === card.dataset.id); if (record?.preference === '偏难吃') { card.querySelector('.repurchase-actions').innerHTML = `<div class="dislike-reason-display">难吃理由：${escapeHtml(record.dislike_reason || '未填写')}</div>`; } else if (record) { const button = card.querySelector('.repurchase-choice[data-value="偏好吃"]'); if (button) button.textContent = '复购仍然好吃'; const actions = card.querySelector('.repurchase-actions'); if (actions && !actions.querySelector('.repurchase-count')) actions.insertAdjacentHTML('beforeend', `<span class="repurchase-count">已复购 ${record.repurchase_count || 0} 次</span>`); } }); };
$('#preference').addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; const field = $('#dislikeReasonField'); const bad = button.dataset.value === '偏难吃'; field.hidden = !bad; $('#dislikeReason').required = bad; if (!bad) $('#dislikeReason').value = ''; });
$('#foodForm').addEventListener('submit', event => { if ($('#preference .selected')?.dataset.value === '偏难吃' && !$('#dislikeReason').value.trim()) { event.preventDefault(); event.stopImmediatePropagation(); $('#dislikeReason').focus(); } }, true);
const nativeFetch = window.fetch;
window.fetch = (url, options) => { if (url === '/api/foods' && options?.method === 'POST') { const data = JSON.parse(options.body); data.dislike_reason = $('#dislikeReason').value.trim(); options.body = JSON.stringify(data); } return nativeFetch(url, options); };
$('#foodForm').addEventListener('reset', () => { flavorOrder.length = 0; });
renderIngredients(); loadRecords();
